

# DATASET PATHS
DATASET_DIR = "./dataset"
TRAIN_LR_TRACK1_X2_DIR = DATASET_DIR + "/DIV2K_train_LR_bicubic/X2"
TRAIN_LR_TRACK1_X3_DIR = DATASET_DIR + "/DIV2K_train_LR_bicubic/X3"
TRAIN_LR_TRACK1_X4_DIR = DATASET_DIR + "/DIV2K_train_LR_bicubic/X4"
TRAIN_LR_TRACK2_X2_DIR = DATASET_DIR + "/DIV2K_train_LR_unknown/X2"
TRAIN_LR_TRACK2_X3_DIR = DATASET_DIR + "/DIV2K_train_LR_unknown/X3"
TRAIN_LR_TRACK2_X4_DIR = DATASET_DIR + "/DIV2K_train_LR_unknown/X4"
VALIDATION_LR_TRACK1_X2_DIR = DATASET_DIR + "/DIV2K_valid_LR_bicubic/X2"
VALIDATION_LR_TRACK1_X3_DIR = DATASET_DIR + "/DIV2K_valid_LR_bicubic/X3"
VALIDATION_LR_TRACK1_X4_DIR = DATASET_DIR + "/DIV2K_valid_LR_bicubic/X4"
VALIDATION_LR_TRACK2_X2_DIR = DATASET_DIR + "/DIV2K_valid_LR_unknown/X2"
VALIDATION_LR_TRACK2_X3_DIR = DATASET_DIR + "/DIV2K_valid_LR_unknown/X3"
VALIDATION_LR_TRACK2_X4_DIR = DATASET_DIR + "/DIV2K_valid_LR_unknown/X4"


# RESULTS PATHS
RESULTS_DIR = "./results"
TRACK1_RESULTS_DIR = RESULTS_DIR + "/track1"
TRACK2_RESULTS_DIR = RESULTS_DIR + "/track2"
TRACK1_BICUBIC_RESULTS_DIR = TRACK1_RESULTS_DIR + "/bicubic"
TRACK2_BICUBIC_RESULTS_DIR = TRACK2_RESULTS_DIR + "/bicubic"